version: "3"

services:
  ingress:
    image: traefik:1.7.6-alpine
    command: --docker --docker.exposedbydefault=false --logLevel=${LOG_LEVEL}
    networks:
      - web
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TZ: "Europe/London"
    volumes:
      - ./data:/data
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=25565"
      - "traefik.frontend.rule=Host:${HOST}"
